### ISSUE TITLE
No error message and no task done

### ISSUE THREAD

**Issue by sebastienserre** [2KAbhishek/gulp-runner#1]
Hello,

Thank you for your action.
I'm trying it (and begin in gulp task too) and unfortunately, no css files are created and no error in the github Action is provided.

Here's my gulpfile.js:
```
const gulp = require('gulp');
const sass = require('gulp-sass');
const cleanCSS = require('gulp-clean-css');
const autoprefixer = require('gulp-autoprefixer');
const sourcemaps = require('gulp-sourcemaps');
const rename = require("gulp-rename");
const cssnano = require('gulp-cssnano');
const mode = require('gulp-mode')();

const srcDir = 'styles/';
const destDir = 'assets/';
const mainScss = 'main.scss';
const mainCss = 'main.css';


gulp.task('sass', function() {
    return gulp.src( srcDir+mainScss)
        .pipe(sass({outputStyle: 'expanded'}))
        .pipe(autoprefixer({
            overrideBrowserslist: ['> 1%']
        }))
        .pipe(gulp.dest( destDir ))
});

gulp.task('minify-css',() => {
    return gulp.src( destDir+mainCss )
        .pipe(sourcemaps.init())
        .pipe(cleanCSS())
        .pipe(sourcemaps.write())
        .pipe(rename({ suffix: '.min' }))
        .pipe(gulp.dest( destDir ));
});

gulp.task('process-sass', () => {
    return gulp.src(srcDir+mainScss)
        .pipe(mode.development(sourcemaps.init()))
        .pipe(sass().on('error', sass.logError))
        .pipe(autoprefixer({
            overrideBrowserslist: ['> 1%']
        }))
        .pipe(cssnano())
        .pipe(mode.development(sourcemaps.write()))
        .pipe(gulp.dest(destDir));
});

gulp.task('watch', function() {
   /* gulp.watch( srcDir+'*.scss',gulp.series('sass'));
    gulp.watch( destDir+mainCss,gulp.series('minify-css'));*/
    gulp.watch( destDir+mainCss,gulp.series('process-sass'));
});
```
My Github action config file is:
```
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm dependencies
        run: npm install
      - name: npm init
        run: npm init -y
      - name: Run build task
        run: npm run build --if-present
      - name: Gulp Runner
        uses: 2KAbhishek/gulp-runner@v0.3
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete --exclude-from='.gitignore'"
          REMOTE_HOST: nXXXX
          REMOTE_PORT: XX
          REMOTE_USER: XXXXX
          TARGET: /XXXXXX
          EXCLUDE: "XXXXX"
```
Do you know what can be wrong ?

Thank you by advance
